# Generated by Django 2.1.15 on 2020-12-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('sexo', models.CharField(choices=[('HOMBRE', 'H'), ('MUJER', 'M')], max_length=10)),
                ('dni', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('monto', models.IntegerField()),
            ],
        ),
    ]
