# Generated by Django 2.1.15 on 2020-12-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
